# Generated by Django 5.2.4 on 2025-08-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID чата Telegram",
            ),
        ),
    ]
