# Generated by Django 5.2.4 on 2025-08-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Название места",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание места"
                    ),
                ),
            ],
            options={
                "verbose_name": ("Место",),
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_action",
                    models.TimeField(verbose_name="Время выполнения"),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=255, verbose_name="Выполняемое действие"
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (2, "Раз в 2 дня"),
                            (3, "Раз в 3 дня"),
                            (4, "Раз в 4 дня"),
                            (5, "Раз в 5 дней"),
                            (6, "Раз в 6 дней"),
                            (7, "Раз в неделю"),
                        ],
                        default=1,
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        verbose_name="Время на выполнение (секунды)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.place",
                        verbose_name="Место выполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Привычка",),
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
