# Generated by Django 5.2.4 on 2025-08-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                max_length=255, verbose_name="Место выполнения"
            ),
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
