# Generated by Django 5.2.4 on 2025-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_place_delete_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Признак активности привычки"
            ),
        ),
    ]
