# Generated by Django 5.2.4 on 2025-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Периодичность (ежедневно)"
            ),
        ),
    ]
