# Generated by Django 5.2.4 on 2025-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Место выполнения",
            ),
        ),
    ]
